package dev.brunofelix.movies.data.remote.dto.movie

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data Transfer Object representing a movie from the TMDB API.
 *
 * @property id Unique identifier for the movie.
 * @property title The title of the movie.
 * @property originalTitle The original title of the movie in its original language.
 * @property originalLanguage The original language of the movie.
 * @property overview A brief summary of the movie's plot.
 * @property posterPath URL or relative path to the movie's poster image.
 * @property backdropPath URL or relative path to the movie's backdrop image.
 * @property releaseDate The date when the movie was released.
 * @property adult Indicates if the movie is for adults only.
 * @property genreIds List of genre IDs associated with the movie.
 * @property popularity Popularity score of the movie.
 * @property video Indicates if the movie has a video (trailer) available.
 * @property voteAverage The average rating given to the movie.
 * @property voteCount The total number of votes received by the movie.
 * @property budget The budget of the movie in USD.
 * @property genres List of [MovieGenreDto] objects representing the genres of the movie.
 * @property homepage URL to the movie's official homepage.
 * @property imdbId The movie's identifier on IMDB.
 * @property originCountry List of countries where the movie originated.
 * @property revenue The total revenue generated by the movie in USD.
 * @property runtime The duration of the movie in minutes.
 * @property status The production status of the movie (e.g., Released, Planned).
 * @property tagline A short catchphrase or slogan for the movie.
 */
@Serializable
data class MovieDto(
    @SerialName("id")
    val id: Long? = null,

    @SerialName("title")
    val title: String? = null,

    @SerialName("original_title")
    val originalTitle: String? = null,

    @SerialName("original_language")
    val originalLanguage: String? = null,

    @SerialName("overview")
    val overview: String? = null,

    @SerialName("poster_path")
    val posterPath: String? = null,

    @SerialName("backdrop_path")
    val backdropPath: String? = null,

    @SerialName("release_date")
    val releaseDate: String? = null,

    @SerialName("adult")
    val adult: Boolean? = null,

    @SerialName("genre_ids")
    val genreIds: List<Int>? = null,

    @SerialName("popularity")
    val popularity: Double? = null,

    @SerialName("video")
    val video: Boolean? = null,

    @SerialName("vote_average")
    val voteAverage: Float? = null,

    @SerialName("vote_count")
    val voteCount: Int? = null,

    @SerialName("budget")
    val budget: Int? = null,

    @SerialName("genres")
    val genres: List<MovieGenreDto>? = null,

    @SerialName("homepage")
    val homepage: String? = null,

    @SerialName("imdb_id")
    val imdbId: String? = null,

    @SerialName("origin_country")
    val originCountry: List<String>? = null,

    @SerialName("revenue")
    val revenue: Long? = null,

    @SerialName("runtime")
    val runtime: Int? = null,

    @SerialName("status")
    val status: String? = null,

    @SerialName("tagline")
    val tagline: String? = null
)
